
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
#    url: jdbc:h2:mem:ggachi
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ggachi?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ggachi
    password: 1234

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQLDialect
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
server:
  port: 10000