
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:ggachi
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true
server:
  port: 10000